import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// Configure your local font
const openSans = localFont({
  src: "../assets/fonts/OpenSans_variable.ttf",
  display: "swap",
  variable: "--font-opensans", // Optional: create a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply flex container classes directly to the body */}
      <body className={`${openSans.className} flex flex-col min-h-screen bg-gray-50`}>
        <Header />

        {/* This is the key change: make <main> a flex container too.
          It will grow to fill the space and manage its children with flexbox.
        */}
        <main className="flex flex-col flex-grow pt-16">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
